### ISSUE TITLE
Issue with latest update on 12/6/2023 7:30PM CST

### ISSUE THREAD

**Issue by andrewmezzo** [Chuckleberry-Finn/MGRS-FMCCYAYFGLE#1]
Everytime I open the map now and drag the map around or move my cursor around it will throw hundreds of these errors: 

I like to think maybe this was a small typo that is causing this, but just wanted to put it on your radar. Thanks!

Errors:

`function: xyToLabel -- file: MGRS_util.lua line # 12 | MOD: Military Grid Reference System For Map Callouts Cause You And Your Friends Get Lost Easily
function: onMouseMove -- file: MGRS.lua line # 47 | MOD: Military Grid Reference System For Map Callouts Cause You And Your Friends Get Lost Easily
java.lang.RuntimeException: __div not defined for operands in xyToLabel
    at se.krka.kahlua.vm.KahluaUtil.fail(KahluaUtil.java:82)
    at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:676)
    at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
    at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
    at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1861)
    at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:135)
    at zombie.ui.UIElement.onMouseMove(UIElement.java:1109)
    at zombie.worldMap.UIWorldMap.onMouseMove(UIWorldMap.java:467)
    at zombie.ui.UIManager.update(UIManager.java:1010)
    at zombie.GameWindow.logic(GameWindow.java:262)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.GameWindow.frameStep(GameWindow.java:765)
    at zombie.GameWindow.run_ez(GameWindow.java:681)
    at zombie.GameWindow.mainThread(GameWindow.java:495)
    at java.base/java.lang.Thread.run(Unknown Source)
`

`function: xyToLabel -- file: MGRS_util.lua line # 12 | MOD: Military Grid Reference System For Map Callouts Cause You And Your Friends Get Lost Easily
function: onMouseMove -- file: MGRS.lua line # 47 | MOD: Military Grid Reference System For Map Callouts Cause You And Your Friends Get Lost Easily
`

**Comment by Chuckleberry-Finn** [comment]
Is this still occuring after the hot fix?

**Comment by andrewmezzo** [comment]
this is fixed thanksSent from my iPhoneOn Dec 9, 2023, at 10:56 AM, Chuckleberry Finn ***@***.***> wrote:﻿
Is this still occuring after the hot fix?
